# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Masha(object):
    def setupUi(self, Masha):
        Masha.setObjectName("Masha")
        Masha.resize(498, 262)
        self.startbtn = QtWidgets.QPushButton(Masha)
        self.startbtn.setGeometry(QtCore.QRect(10, 70, 481, 81))
        self.startbtn.setObjectName("start")
        self.label = QtWidgets.QLabel(Masha)
        self.label.setGeometry(QtCore.QRect(10, 10, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Masha)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 481, 81))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 461, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.indexknow = QtWidgets.QPushButton(self.groupBox_2)
        self.indexknow.setGeometry(QtCore.QRect(320, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.indexknow.setFont(font)
        self.indexknow.setObjectName("indexknow")
        self.infoindex = QtWidgets.QPushButton(self.groupBox_2)
        self.infoindex.setGeometry(QtCore.QRect(431, 20, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.infoindex.setFont(font)
        self.infoindex.setObjectName("infoindex")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Masha)
        self.label_2.setGeometry(QtCore.QRect(10, 240, 71, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Masha)
        QtCore.QMetaObject.connectSlotsByName(Masha)

    def retranslateUi(self, Masha):
        _translate = QtCore.QCoreApplication.translate
        Masha.setWindowTitle(_translate("Masha", "Masha"))
        Masha.setWindowIcon(QtGui.QIcon('ICON.ico'))
        self.startbtn.setText(_translate("Masha", "Старт"))
        self.label.setText(_translate("Masha", "Masha voice assistant"))
        self.groupBox.setTitle(_translate("Masha", "Настройки"))
        self.groupBox_2.setTitle(_translate("Masha", "Индекс микрофона"))
        self.indexknow.setText(_translate("Masha", "Узнать индекс"))
        self.infoindex.setText(_translate("Masha", "?"))
        self.label_2.setText(_translate("Masha", "by cl0vvn_"))

